### ISSUE TITLE
Import in Anytone CPS 1.15

### ISSUE THREAD

**Issue by Fribbler** [BM-Database/database#3]
Ik krijg de userat.csv niet meer goed in de Anytone CPS 1.15 geimporteerd, een oude file (van juli) ging wel goed. Is er iets veranderd? Volgens mij heeft de beta hetzelfde, maar dat heb ik niet ge-dubbel-checked.

![Voorbeeld](https://www.mupload.nl/img/7ed3ld.png)

Zie:
(https://www.dmrtechnoronde.nl/index.php?topic=550.20)

73 de PE2ERK
Erik

**Comment by javastraat** [comment]
bedankt voor het melden
een script drijde niet goed en hierdoor zijn tijdens dos2unix conversatie teveel characters weg gehaald (^M,lf,br etc)
dit is nu opgelost en getest door pd1wp en mezelf

cu6 met de nieuwe database

73 gr
Andy aka PD2EMC
