### ISSUE TITLE
Can not download or save as Anytone csv file

### ISSUE THREAD

**Issue by RicGB** [BM-Database/database#4]
![image](https://user-images.githubusercontent.com/27000329/69493604-de9bb200-0eb0-11ea-9776-3a69cdb2c4ec.png)
  I'm using edge and edge chromium, no one can download under windows 10

**Comment by javastraat** [comment]
thanx for making this issue
I tried to downloaded and viewed the raw file with windows 10 (1909/18363. 476) and edge and it all works, also it works win w10 with chrome and firefox

https://raw.githubusercontent.com/BM-Database/database/master/userat.csv

download tool works also fine

this issue if it keeps coming is a GitHub issue and not database related issue
