### ISSUE TITLE
DMR UserDB has wrong name

### ISSUE THREAD

**Issue by Billy2k14** [BM-Database/database#5]
DMR UserDB has wrong name

it should be Billy (NOT William)

Callsign M6GZI

**Comment by javastraat** [comment]
thanx for the heads up, will be updated in the next release

stay safe and at home if possible 73 PD2EMC

**Comment by Billy2k14** [comment]
Thank you, 73 M6GZI

Sent from Yahoo Mail on Android 
 
  On Sun, Apr 19, 2020 at 9:24 PM, Albert Einstein<notifications@github.com> wrote:   


thanx for the heads up, will be updated in the next release

stay safe and at home if possible 73 PD2EMC
