### ISSUE TITLE
Some entries seem to be incorrect

### ISSUE THREAD

**Issue by jimbobshazham** [BM-Database/database#6]
Mine for example, my dmr id is 2345247. I am certainly not a jason from london with an m6 callsign. If you compare your .csv files to those of [radioid.net ](https://radioid.net/static/user.csv) you will see the error. can someone sort this as I'm beginning to get people accuse me of impersonating someone.

**Comment by javastraat** [comment]
this entry by radionet 2345247,M7KMW,Opt,,,,United Kingdom, is correct ?
its all volunteer work, excuus for the incorect entry
and if poeple accuse you, im sad to here that

if you can confirm the above entry or anything you want in it we can change this of course in the database

stay safe 73 PD2EMC aka Andy

**Comment by jimbobshazham** [comment]
Yes the information you posted is correct would be brilliant if you could correct it.

**Comment by javastraat** [comment]
i will mail it now to pd1wp in the next release it will be fixed

sorry for the inconvenience
stay safe
