### ISSUE TITLE
Users.cvs is outdated

### ISSUE THREAD

**Issue by baxterdmutt** [BM-Database/database#8]
Looking through the users.csv download and it is very very much out of date. I thought these were now updated regularly again, but my callsign location was edited in radioid.net well over a year ago and the DB still shows my old location. 
Sorry for posting in the wrong place initially.

**Comment by baxterdmutt** [comment]
Just to confirm I’m talking about the data that is downloaded when tools application is run. I’m not sure if that’s this database or the beta database or if they are the same. Einstein, I sent you my callsign but it’s not just me. I see lots of ids coming up that have no callsign in your database. Some of these are people that I know have had an id for months. For example my location was updated in radioid.net at least 2 years ago.

**Comment by javastraat** [comment]
this is the old database

your entry in database-beta looks like 

xxxx,xxxx,VA7VH,Roger,Armstrong,British Columbia,Canada,,Private Call,None


so our data is ok, unless you moved again.
and we dont have a users.csv

and what tool do you use ?

**Comment by baxterdmutt** [comment]
Ok but that’s not what gets downloaded by the tools app. The data it’s bringing in is outdated. I just did it yesterday and it showed my address as the one from 3 years ago. RogerOn Jun 20, 2023, at 22:59, Albert Einstein ***@***.***> wrote:﻿
this is an old database
your entry looks like
xxxx,xxxx,VA7VH,Roger,Armstrong,British Columbia,Canada,,Private Call,None
sp our data is ok

**Comment by javastraat** [comment]
maybe give us some info ?
what tool do u use? latest version of it ?
what for ht ?

etc etc

you complain but wont give any info, i am already days busy with you. and all i can tell you is that the data in database-beta is correct on all files and our tools (the latest version) downloads the correct database

**Comment by baxterdmutt** [comment]
RogerOn Jun 21, 2023, at 09:04, Roger Andrews ***@***.***> wrote:﻿Ok but that’s not what gets downloaded by the tools app. The data it’s bringing in is outdated. I just did it yesterday and it showed my address as the one from 3 years ago. RogerOn Jun 20, 2023, at 22:59, Albert Einstein ***@***.***> wrote:﻿
this is an old database
your entry looks like
xxxx,xxxx,VA7VH,Roger,Armstrong,British Columbia,Canada,,Private Call,None
sp our data is ok

**Comment by javastraat** [comment]
what tool do you use? we got more than one. what version ? what version of ht ?
